"use client";


export default function TrustedSection() {
    return (
        <section className="relative z-10 py-24 px-6 overflow-hidden">
            {/* Background Elements */}
            <div className="absolute inset-0 bg-background-dark pointer-events-none" />
            <div className="absolute top-1/2 left-1/4 w-96 h-96 bg-primary/20 rounded-full blur-[100px] -z-10" />

            <div className="max-w-[1200px] mx-auto">

                {/* Section Header */}
                <div className="text-center mb-20">
                    <h2 className="font-serif text-4xl md:text-5xl text-white mb-4">
                        Join the <span className="text-primary italic">Viral Club</span>
                    </h2>
                    <p className="text-gray-400 max-w-2xl mx-auto">
                        Our creators don&apos;t just post content. They dominate the feed.
                        See the impact of premium assets on real accounts.
                    </p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-20">
                    {/* Metric 1 */}
                    <div className="p-8 bg-white/5 border border-white/10 rounded-2xl backdrop-blur-sm hover:border-primary/50 transition-colors group">
                        <div className="flex items-center gap-4 mb-4">
                            <div className="w-12 h-12 rounded-full bg-primary/20 flex items-center justify-center text-primary">
                                <span className="material-symbols-outlined">visibility</span>
                            </div>
                            <h3 className="text-4xl font-bold text-white group-hover:scale-110 transition-transform">10M+</h3>
                        </div>
                        <p className="text-gray-400">Total views generated by our Reel Bundles in the last 30 days.</p>
                    </div>

                    {/* Metric 2 */}
                    <div className="p-8 bg-white/5 border border-white/10 rounded-2xl backdrop-blur-sm hover:border-emerald-500/50 transition-colors group">
                        <div className="flex items-center gap-4 mb-4">
                            <div className="w-12 h-12 rounded-full bg-emerald-500/20 flex items-center justify-center text-emerald-400">
                                <span className="material-symbols-outlined">group_add</span>
                            </div>
                            <h3 className="text-4xl font-bold text-white group-hover:scale-110 transition-transform">500k+</h3>
                        </div>
                        <p className="text-gray-400">New followers gained by creators using our Growth Strategies.</p>
                    </div>

                    {/* Metric 3 */}
                    <div className="p-8 bg-white/5 border border-white/10 rounded-2xl backdrop-blur-sm hover:border-amber-500/50 transition-colors group">
                        <div className="flex items-center gap-4 mb-4">
                            <div className="w-12 h-12 rounded-full bg-amber-500/20 flex items-center justify-center text-amber-400">
                                <span className="material-symbols-outlined">monetization_on</span>
                            </div>
                            <h3 className="text-4xl font-bold text-white group-hover:scale-110 transition-transform">$1M+</h3>
                        </div>
                        <p className="text-gray-400">Revenue generated by students of our Digital Product Blueprint.</p>
                    </div>
                </div>

                {/* Success Story Spotlight */}
                <div className="bg-gradient-to-r from-zinc-900 to-black border border-white/10 rounded-3xl p-8 md:p-12 flex flex-col md:flex-row items-center gap-12">
                    {/* Chart Visual */}
                    <div className="w-full md:w-1/2 relative h-64 bg-black/50 rounded-xl border border-white/5 overflow-hidden flex items-end justify-between px-8 pb-0 pt-12 group">
                        <div className="absolute top-4 left-4 text-xs text-gray-500 uppercase tracking-widest">Account Growth (30 Days)</div>

                        {/* Bars */}
                        <div className="w-8 bg-zinc-800 rounded-t-md h-[10%]" />
                        <div className="w-8 bg-zinc-800 rounded-t-md h-[15%]" />
                        <div className="w-8 bg-zinc-700 rounded-t-md h-[25%]" />
                        <div className="w-8 bg-zinc-700 rounded-t-md h-[40%]" />
                        <div className="w-8 bg-zinc-600 rounded-t-md h-[55%]" />
                        <div className="w-8 bg-primary/50 rounded-t-md h-[70%] animate-pulse" />
                        <div className="w-8 bg-primary rounded-t-md h-[95%] shadow-[0_0_20px_rgba(43,230,255,0.4)]" />

                        {/* Trend Line Overlay */}
                        <svg className="absolute inset-0 w-full h-full pointer-events-none" preserveAspectRatio="none">
                            <path d="M 30 200 Q 150 180, 250 100 T 500 20" fill="none" stroke="#2be6ff" strokeWidth="4" strokeLinecap="round" className="drop-shadow-[0_0_10px_rgba(43,230,255,0.8)]" />
                        </svg>
                    </div>

                    {/* Text */}
                    <div className="w-full md:w-1/2 text-left">
                        <div className="flex items-center gap-4 mb-4">
                            <img src="https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=100&h=100" alt="Sarah" className="w-16 h-16 rounded-full border-2 border-primary object-cover" />
                            <div>
                                <h4 className="text-xl font-bold text-white">Sarah Jenkins</h4>
                                <p className="text-primary text-sm">@sarah.creates</p>
                            </div>
                        </div>
                        <p className="text-2xl text-white font-serif italic leading-relaxed mb-6">
                            {`"I was stuck at 500 followers for months. I downloaded the `}<span className="text-primary not-italic">Faceless Marketing Bundle</span>{` and hit 10k in just 3 weeks. The templates are literally a cheat code."`}
                        </p>
                        <div className="flex gap-4 text-xs text-gray-500 font-mono uppercase tracking-widest">
                            <span>Product: Faceless Bundle</span>
                            <span>•</span>
                            <span>Result: 20x Growth</span>
                        </div>
                    </div>
                </div>

            </div>
        </section>
    );
}
